SGROUP      GROUP   CODE_SEG, DATA_SEG
            ASSUME  CS:SGROUP, DS:SGROUP, SS:SGROUP

    TRUE  EQU 1
    FALSE EQU 0

    ASCII_SPECIAL_KEY EQU 00
    ASCII_LEFT        EQU 04Bh
    ASCII_RIGHT       EQU 04Dh
    ASCII_UP          EQU 048h
    ASCII_QUIT        EQU 071h 

    ASCII_PLAYER      EQU 02Ah 
    ATTR_PLAYER       EQU 00Fh 
    ASCII_WALL        EQU 0DBh 
    
    CURSOR_SIZE_HIDE  EQU 02607h
    SCREEN_MAX_ROWS   EQU 25
    SCREEN_MAX_COLS   EQU 80

    FIELD_C1 EQU 25
    FIELD_C2 EQU 55

CODE_SEG    SEGMENT PUBLIC
            ORG 100h

MAIN    PROC    NEAR
    MOV AX, CS
    MOV DS, AX

    CALL REGISTER_TIMER_INTERRUPT
    CALL INIT_GAME
    CALL INIT_SCREEN
    CALL HIDE_CURSOR
    CALL DRAW_INITIAL_WALLS 

    MOV BYTE PTR [POS_R], SCREEN_MAX_ROWS - 5
    MOV BYTE PTR [POS_C], (FIELD_C1 + FIELD_C2) / 2
        
MAIN_LOOP:
    CMP BYTE PTR [END_GAME], TRUE
    JE JUMP_TO_END
    
    MOV AH, 0Bh
    INT 21h
    CMP AL, 0
    JE MAIN_LOOP 

    CALL READ_CHAR      
    CMP AL, ASCII_QUIT
    JE JUMP_TO_END
    
    CMP AL, ASCII_SPECIAL_KEY
    JNE MAIN_LOOP
    
    CALL READ_CHAR 
    
    CMP AL, ASCII_LEFT
    JE LEFT_KEY
    CMP AL, ASCII_RIGHT
    JE RIGHT_KEY
    CMP AL, ASCII_UP
    JE UP_KEY
    JMP MAIN_LOOP

JUMP_TO_END: JMP END_PROG

LEFT_KEY:
    MOV BYTE PTR [INC_COL], -1
    JMP MAIN_LOOP
RIGHT_KEY:
    MOV BYTE PTR [INC_COL], 1
    JMP MAIN_LOOP
UP_KEY:
    MOV BYTE PTR [INC_ROW], -1
    JMP MAIN_LOOP

END_PROG:
    CALL RESTORE_TIMER_INTERRUPT
    MOV AX, 0003h 
    INT 10h
    INT 20h     
MAIN    ENDP    

NEW_TIMER_INTERRUPT PROC NEAR
    PUSHF
    CALL DWORD PTR [OLD_INTERRUPT_BASE] 
    
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH DS

    MOV AX, CS
    MOV DS, AX

    INC BYTE PTR [INT_COUNT]
    MOV AL, BYTE PTR [INT_COUNT]
    CMP AL, BYTE PTR [DIV_SPEED]
    JE DO_LOGIC
    JMP EXIT_ISR 

DO_LOGIC:
    MOV BYTE PTR [INT_COUNT], 0

   
    MOV DH, BYTE PTR [POS_R]
    MOV DL, BYTE PTR [POS_C]
    CALL MOVE_CURSOR
    MOV AL, ' '
    MOV BL, 0
    CALL PRINT_CHAR_ATTR

   
    MOV AL, BYTE PTR [INC_COL]
    ADD BYTE PTR [POS_C], AL
    MOV AL, BYTE PTR [INC_ROW]
    ADD BYTE PTR [POS_R], AL
    
    MOV BYTE PTR [INC_COL], 0
    MOV BYTE PTR [INC_ROW], 0

  
    CMP BYTE PTR [POS_R], 5
    JAE SKIP_SCROLL
    
   
    MOV AX, 0701h 
    MOV BH, 07h 
    XOR CX, CX
    MOV DX, 184Fh 
    INT 10h
    MOV BYTE PTR [POS_R], 6 

SKIP_SCROLL:
    INC BYTE PTR [WALL_COLOR]
    MOV AL, BYTE PTR [WALL_COLOR]
    AND AL, 0Fh 
    JNZ D_WALLS
    MOV BYTE PTR [WALL_COLOR], 1 

D_WALLS:
    MOV AL, ASCII_WALL
    MOV BL, BYTE PTR [WALL_COLOR]
    MOV DH, 0
    MOV DL, FIELD_C1
    CALL MOVE_CURSOR
    CALL PRINT_CHAR_ATTR
    MOV DL, FIELD_C2
    CALL MOVE_CURSOR
    CALL PRINT_CHAR_ATTR

DRAW_PLAYER:
   
    MOV AL, BYTE PTR [POS_C]
    CMP AL, FIELD_C1
    JBE TRIGGER_COLLISION
    CMP AL, FIELD_C2
    JAE TRIGGER_COLLISION

    
    MOV DH, BYTE PTR [POS_R]
    MOV DL, BYTE PTR [POS_C]
    CALL MOVE_CURSOR
    MOV AL, ASCII_PLAYER
    MOV BL, ATTR_PLAYER
    CALL PRINT_CHAR_ATTR
    JMP EXIT_ISR

TRIGGER_COLLISION:
    MOV BYTE PTR [END_GAME], TRUE

EXIT_ISR:
    POP DS
    POP DX
    POP CX
    POP BX
    POP AX
    IRET
NEW_TIMER_INTERRUPT ENDP



DRAW_INITIAL_WALLS PROC NEAR
    MOV CX, SCREEN_MAX_ROWS
    MOV DH, 0
LOOP_W:
    PUSH CX
    MOV DL, FIELD_C1
    CALL MOVE_CURSOR
    MOV AL, ASCII_WALL
    MOV BL, 07h 
    CALL PRINT_CHAR_ATTR
    MOV DL, FIELD_C2
    CALL MOVE_CURSOR
    CALL PRINT_CHAR_ATTR
    INC DH
    POP CX
    LOOP LOOP_W
    RET
DRAW_INITIAL_WALLS ENDP

INIT_GAME PROC NEAR
    MOV BYTE PTR [INC_COL], 0
    MOV BYTE PTR [INC_ROW], 0
    MOV BYTE PTR [DIV_SPEED], 2 
    MOV BYTE PTR [END_GAME], FALSE
    MOV BYTE PTR [WALL_COLOR], 1
    RET
INIT_GAME ENDP

INIT_SCREEN PROC NEAR
    MOV AX, 0003h 
    INT 10h
    RET
INIT_SCREEN ENDP

HIDE_CURSOR PROC NEAR
    MOV AH, 01h
    MOV CX, CURSOR_SIZE_HIDE
    INT 10h
    RET
HIDE_CURSOR ENDP

MOVE_CURSOR PROC NEAR
    MOV AH, 02h
    XOR BX, BX
    INT 10h
    RET
MOVE_CURSOR ENDP

PRINT_CHAR_ATTR PROC NEAR
    MOV AH, 09h
    XOR BH, BH
    MOV CX, 0001h
    INT 10h
    RET
PRINT_CHAR_ATTR ENDP

READ_CHAR PROC NEAR
    MOV AH, 08h 
    INT 21h
    RET
READ_CHAR ENDP

REGISTER_TIMER_INTERRUPT PROC NEAR
    MOV AX, 3508h 
    INT 21h
    MOV WORD PTR [OLD_INTERRUPT_BASE + 2], ES
    MOV WORD PTR [OLD_INTERRUPT_BASE], BX
    MOV AX, 2508h 
    MOV DX, OFFSET NEW_TIMER_INTERRUPT
    INT 21h
    RET
REGISTER_TIMER_INTERRUPT ENDP

RESTORE_TIMER_INTERRUPT PROC NEAR
    PUSH DS
    MOV DX, WORD PTR [OLD_INTERRUPT_BASE]
    MOV DS, WORD PTR [OLD_INTERRUPT_BASE + 2]
    MOV AX, 2508h
    INT 21h
    POP DS
    RET
RESTORE_TIMER_INTERRUPT ENDP

CODE_SEG ENDS

DATA_SEG SEGMENT PUBLIC
    OLD_INTERRUPT_BASE DW 0, 0
    INC_COL    DB 0
    INC_ROW    DB 0
    POS_R      DB 0
    POS_C      DB 0
    DIV_SPEED  DB 0
    INT_COUNT  DB 0
    END_GAME   DB 0
    WALL_COLOR DB 1
DATA_SEG ENDS

END MAIN